(function(window,$,undefined){var phoenixSite=window.phoenixSite||(window.phoenixSite={});var COOKIE_KEY="PFCC";var prodList=phoenixSite.prodList||(phoenixSite.prodList={});var _options={};var isFrontend=window.$_phoenix==undefined;$.extend(prodList,{init:function(options){$.extend(_options,options);prodList.bindFrontEvent()},bindFrontEvent:function(){var _hasProducts=_options.hasProducts;var selectProductListStyle=_options.selectProductListStyle;var widgetClass=_options.widgetClass;var phoenix_product_more_des=
_options.phoenix_product_more_des;var phoenix_product_closed=_options.phoenix_product_closed;var phoenix_shopingcart_notice=_options.phoenix_shopingcart_notice;var phoenix_error_buy_prod=_options.phoenix_error_buy_prod;var payModuleFlag=_options.payModuleFlag;var prodPhotoSize=_options.prodPhotoSize;var categoryIdPagination=_options.phoenix_categoryIdPagination;if(!_hasProducts)return;if(categoryIdPagination=="-1")$.cookie("PFCC","",{expires:-1});else $.cookie("PFCC","productGroupId_"+categoryIdPagination,
{expires:24*60*60,path:"/"});if(selectProductListStyle=="0"){var setWidthClass=function(obj){var obj=obj;var className="";var prodlistParameterWrap=0;obj.find(".prodlist-parameter-wrap").removeAttr("style").each(function(){if($(this).height()>prodlistParameterWrap)prodlistParameterWrap=$(this).height()}).css("height",prodlistParameterWrap);obj.each(function(){_that=$(this);var $picbox=_that.find(".prodlist-picbox");var winWidth=parseInt(_that.width());if(winWidth<=225)className="piclist-all profixlist480";
else if(winWidth<=280)className="piclist140 profixlist480";else if(winWidth<=310)className="piclist320 profixlist480";else if(winWidth<=365)className="piclist360 profixlist480";else if(winWidth<=415)className="piclist180 profixlist480";else if(winWidth<=480)className="piclist960 profixlist480";else if(winWidth<=580)className="piclist180 profixlist740";else if(winWidth<=680)className="piclist480 profixlist740";else if(winWidth<=740)className="piclist230 profixlist740";else if(winWidth<=800)className=
"piclist180 profixlist960";else if(winWidth<=960)className="piclist900 profixlist960";else if(winWidth<=980)className="piclist960 profixlist1180";else if(winWidth<=1180)className="piclist1180 profixlist1180";else if(winWidth<=2E3)className="piclist1180 profixlistfull";var lastwidthName=_that.attr("widthName");_that.attr("widthName",className).removeClass(lastwidthName).addClass(className);var liwidth=_that.find(".prodlist-fix-num li").width();function ratio(prodPhotoSize){switch(prodPhotoSize){case "0":return liwidth;
case "1":return liwidth*2/3;case "2":return liwidth*3/2;case "3":return liwidth*3/4;case "4":return liwidth*4/3;case "5":return liwidth*9/16;case "6":return liwidth*16/9}}_that.find(".prodlist-fix-num .prodlist-display").width(liwidth-12).height(ratio(prodPhotoSize)-12)})};setWidthClass($("."+widgetClass));$(window).on("resize.prodList",function(){setWidthClass($("."+widgetClass))})}else if(selectProductListStyle=="4"||selectProductListStyle=="1"||selectProductListStyle=="5"){var setdbWidthClass=
function(obj){var obj=obj;var dbclassName="";obj.each(function(){_that=$(this);var winWidth=parseInt(_that.width());if(winWidth>=960)dbclassName="dbPro960";else if(winWidth>=780)dbclassName="dbPro780";else if(winWidth>=680)dbclassName="dbPro680";else if(winWidth>=470)dbclassName="dbPro470";else if(winWidth>=380)dbclassName="dbPro380";else if(winWidth>=280)dbclassName="dbPro280";else dbclassName="dbPro225";_that.find("li:even").addClass("even");_that.find("li:odd").addClass("odd");var lastwidthName=
_that.attr("dbclassName");_that.attr("dbclassName",dbclassName).removeClass(lastwidthName).addClass(dbclassName)})};setdbWidthClass($("."+widgetClass));$(window).resize(function(){setdbWidthClass($("."+widgetClass))})}if(selectProductListStyle=="5")$(".prodlist-lists-right .prodDeshow a").click(function(){var $prodDesc=$(this).parents(".prodlist-box-hover").find(".prodDesc");if($prodDesc.is(":visible")){$prodDesc.hide();$(this).text(phoenix_product_more_des)}else{$prodDesc.show();$(this).text(phoenix_product_closed);
tableScroll($prodDesc[0])}return false});phoenixSite.sitewidgets.showcaseScrollEffect=function(obj,EFFECT,OPP,Marquee){var ulW=$(obj).width();var listW=$(obj+" li").width();var res=parseInt(ulW/listW)>1?parseInt(ulW/listW):1;if(undefined==Marquee||Marquee)$(obj).slide({mainCell:"\x3eul",autoPage:true,effect:EFFECT,autoPlay:true,vis:res,interTime:50,trigger:"click",opp:OPP});else $(obj).slide({mainCell:"\x3eul",autoPage:true,effect:"leftLoop",scroll:res,autoPlay:true,vis:res,interTime:2500,trigger:"click",
opp:OPP});$(obj).find(".tempWrap").css("width","100%");var showcaseScroll=null;$(window).resize(function(){if(showcaseScroll)clearTimeout(showcaseScroll);showcaseScroll=setTimeout(function(){$(obj).find(".tempWrap").css("width","100%")},200)})};if(selectProductListStyle=="0")phoenixSite.sitewidgets.prodListMargins("."+widgetClass+" .prodlist-showcase-margindisplay",5);else if(selectProductListStyle=="3")phoenixSite.sitewidgets.showcaseScrollEffect("."+widgetClass+" .prodlist-showcase-loopscroll",
"leftMarquee",true,false);else if(selectProductListStyle=="2")phoenixSite.sitewidgets.showcaseScrollEffect("."+widgetClass+" .prodlist-showcase-btnscroll","leftLoop",true,false);if($(".prodlist-pro-inquire")[0]!=undefined&&isFrontend)$(".prodlist-pro-inquire").unbind("click").bind("click",function(){var prodId=$(this).attr("prodId");var inquireParam={prodId:prodId,selectParam:""};var arrayInquire=new Array;arrayInquire.push(inquireParam);$("."+widgetClass+" input[name\x3dinquireParams]").val($.toJSON(arrayInquire));
$("#prodsInquire").submit()});$("."+widgetClass+" #prodAddCart").unbind("click").bind("click",function(){var that=$(this);if(payModuleFlag=="1"&&$("."+widgetClass+" .prodlist-discountprice")[0]==undefined){$("\x3cdiv class\x3d'add-cart-msg'\x3e"+phoenix_error_buy_prod+"\x3c/div\x3e").appendTo($("body"));var popUpWin=$(".add-cart-msg");$(popUpWin).fadeIn(500);setTimeout(function(){$(popUpWin).fadeOut(500,function(){$(this).remove()})},1500);return}var _url="/phoenix/admin/order/addToCart";var type=
"post";var quantity="1";var prodId=that.attr("prodId");var propertyIds=$.trim(that.attr("skuValueId"));var data={"extendProp":propertyIds,"quantity":quantity,"prodIds":prodId};var _options={url:_url,type:type,dataType:"json",data:data,done:function(xhr){if(xhr.status=="success"){var msg=phoenix_shopingcart_notice;$("\x3cdiv class\x3d'add-cart-msg'\x3e"+msg+"\x3c/div\x3e").appendTo($("body"));var popUpWin=$(".add-cart-msg");$(popUpWin).fadeIn(500);setTimeout(function(){$(popUpWin).fadeOut(500,function(){$(this).remove()})},
1500);if(xhr.addNewFlag!=undefined)$(".sitewidget-shoppingStatus span[data-attr\x3dshoppingcartNum]").each(function(i,n){var oldNum=$(n).html();oldNum=oldNum.replace(/\d+/,xhr.cartNum);$(n).html(oldNum)});showLayerShopcart()}else{if(typeof xhr["prodDetail"]!="undefined"&&!!xhr["prodDetail"]){window.location.href=xhr["prodDetail"];return}that.next("span#addToCartErrorMsg").html(xhr.reason).show().fadeOut(5E3)}}};phoenixSite.ajax(_options)})}});function showLayerShopcart(){if(!!phoenixSite.shoppingcartStatus&&
typeof phoenixSite.shoppingcartStatus.showLayerShopcart=="function")phoenixSite.shoppingcartStatus.showLayerShopcart()}})(window,jQuery);