(function(window,$,undefined){var phoenixSite=window.phoenixSite||(window.phoenixSite={});var basket=phoenixSite.basket||(phoenixSite.basket={});var prodIdArray=basket.prodIdArray||(basket.prodIdArray=[]);$.extend(basket,{init:function(){var ignoreShowBasketValue=$.trim($("input[data-attr\x3dignoreShowBasket]:hidden").val());if(!!ignoreShowBasketValue)return;if(!!!localStorage)return;var baksetProdArray=localStorage.getItem("baksetProdArray");var prodIdArray_l="";var inquire_LiAll="";if(!!baksetProdArray){prodIdArray=
JSON.parse(baksetProdArray);basket.prodIdArray=prodIdArray;prodIdArray_l=prodIdArray.length}else prodIdArray_l=0;var _ask_delete=phoenixSite.message(phoenixSite.lanEdition,"phoenix_common_delete");for(var i=0;i<prodIdArray_l;i++)inquire_LiAll+="\x3cli prodId\x3d"+prodIdArray[i]["prodId"]+"\x3e"+'\x3ca class\x3d"basket-list-img" href\x3d"javaScript:;" title\x3d""\x3e\x3cimg src\x3d"'+prodIdArray[i]["prodPhotoUrl"]+'" height\x3d"45"\x3e\x3c/a\x3e'+'\x3ca href\x3d"javaScript:;" title\x3d"" class\x3d"basket-list-name"\x3e'+
prodIdArray[i]["prodName"]+"\x3c/a\x3e"+'\x3cinput type\x3d"hidden" name\x3d"selectParam" value\x3d"'+(prodIdArray[i]["selectParam"]||"")+'" /\x3e'+'\x3cinput type\x3d"hidden" name\x3d"skuParam" value\x3d"'+(prodIdArray[i]["skuParam"]||"")+'" /\x3e'+'\x3cinput type\x3d"hidden" name\x3d"quantity" value\x3d"'+(prodIdArray[i]["quantity"]||"")+'" /\x3e'+'\x3ca href\x3d"javaScript:;" title\x3d"" class\x3d"basket-list-delate"\x3e'+_ask_delete+"\x3c/a\x3e\x3c/li\x3e";var _ask_value=phoenixSite.message(phoenixSite.lanEdition,
"phoenix_inquire_basket");var _ask_value_button=phoenixSite.message(phoenixSite.lanEdition,"phoenix_inquire_button");var _ask_value_empty=phoenixSite.message(phoenixSite.lanEdition,"phoenix_empty");var _html='\x3cdiv id\x3d"prodInquireBasket" class\x3d"inquire-basket-listwrap" style\x3d"display:none;"\x3e'+'\x3cform id\x3d"basketForm" action\x3d"/phoenix/admin/prod/inquire" method\x3d"post"\x3e'+'\x3cdiv class\x3d"basket-title"\x3e'+'\x3cspan class\x3d"basket-title-clickshow"\x3e'+'\x3cspan class\x3d"basket-title-fonts"\x3e'+
_ask_value+' (\x3cspan id\x3d"selectInquireCount" class\x3d"basket-title-pronum"\x3e'+prodIdArray_l+"\x3c/span\x3e)\x3c/span\x3e"+"\x3c/span\x3e"+'\x3ci class\x3d"basket-title-thumb"\x3e\x3c/i\x3e'+"\x3c/div\x3e"+'\x3cdiv class\x3d"basket-lists-animatewrap"\x3e'+'\x3cdiv class\x3d"basket-lists"\x3e'+'\x3cul class\x3d"fix"\x3e'+inquire_LiAll+"\x3c/ul\x3e"+"\x3c/div\x3e"+'\x3cdiv class\x3d"basket-btns fix"\x3e\x3cbutton id\x3d"basketEmpty"\x3e'+_ask_value_empty+'\x3c/button\x3e\x3cbutton id\x3d"basketInquire" class\x3d"flr" type\x3d"submit"\x3e'+
_ask_value_button+"\x3c/button\x3e\x3c/div\x3e"+"\x3c/div\x3e"+'\x3cinput type\x3d"hidden" name\x3d"inquireParams" /\x3e'+"\x3c/form\x3e"+"\x3c/div\x3e";$("body").append(_html);phoenixSite.sitewidgets.basketThumbToggle();if(!!baksetProdArray)$("#prodInquireBasket").removeAttr("style");var selectInquireCount=$("#selectInquireCount").html();var shoppingIcon=$('\x3cdiv class\x3d"shoppingBasketIcon"\x3e\x3ci class\x3d"fa fa-shopping-cart" aria-hidden\x3d"true"\x3e\x3c/i\x3e\x3cspan id\x3d"shoppingIconNum"\x3e\x3c/span\x3e\x3c/div\x3e');
$("body").append(shoppingIcon);if(!isNaN(parseInt(selectInquireCount))&&parseInt(selectInquireCount)>0){$(".shoppingBasketIcon span").addClass("shoppingIconNum");$("#shoppingIconNum").html(parseInt(selectInquireCount))}else shoppingIcon.hide();$("body").on("click","#basketEmpty",function(){$(".remove-basket-data").triggerHandler("click");return false});shoppingIcon.on("click",function(){if(!$(this).hasClass("on")){$("#prodInquireBasket").slideDown();$(this).addClass("on")}else{$(this).removeClass("on");
$("#prodInquireBasket").slideUp()}});if(!isNaN(parseInt(selectInquireCount))&&parseInt(selectInquireCount)==0){$("#prodInquireBasket").slideUp();$(".shoppingBasketIcon").removeClass("on")}$("#basketInquire").unbind("click").bind("click",function(){basket.submitInquireBasket();$("#basketForm").submit()});$(".inquire-basket-listwrap .basket-title").append('\x3cspan class\x3d"remove-basket-data hide"\x3e\x3ci class\x3d"fa fa-trash"\x3e\x3c/i\x3e\x3c/span\x3e');basket.bindDeleteInquireProd();$(document).on("click",
".prodlist-pro-inquire",function(){var prodId=$(this).attr("prodId");var inquireParam={prodId:prodId,selectParam:""};var arrayInquire=new Array;arrayInquire.push(inquireParam);$(" input[name\x3dinquireParams]").val($.toJSON(arrayInquire));$(" #prodsInquire").submit()});$(".pro-detail-basket").unbind("click").bind("click",function(){if(!!!localStorage)return;var prodId=$(this).attr("prodId");var prodPhotoUrl=$(this).attr("prodPhotoUrl");var prodName=$(this).attr("prodName");var prodSelectParam="";
var prodDetailDiv=$(".pro-detail-basket").parents(".sitewidget-proddetail");var selectParamStr="";var skuParamStr="";var quantityStr="";var quantity="";if(prodDetailDiv[0]!=undefined){var isNewProd="1"==$("#isSkuProd").val();if(isNewProd){var skuValueId=$("#skuValueId").val()||"";skuParamStr=skuValueId;prodSelectParam='\x3cinput type\x3d"hidden" name\x3d"skuParam" value\x3d\''+skuValueId+'\' /\x3e\x3cinput type\x3d"hidden" name\x3d"selectParam" value\x3d"" /\x3e';prodPhotoUrl=!!$("#skuImgUrl").val()?
$("#skuImgUrl").val():prodPhotoUrl;selectParamStr=""}else{var aChoosed=prodDetailDiv.find("a.choosed");if(aChoosed[0]!=undefined){var selectParam={};aChoosed.each(function(i,n){var name=$(n).parent().parent().parent().children("th").html();var selectValue=$(n).attr("title");selectParam[name]=selectValue});selectParamStr=$.toJSON(selectParam);prodSelectParam='\x3cinput type\x3d"hidden" name\x3d"skuParam" value\x3d"" /\x3e\x3cinput type\x3d"hidden" name\x3d"selectParam" value\x3d\''+selectParamStr+
"' /\x3e";skuParamStr=""}}quantity=$("input.order-quan-input").val()||"";quantityStr='\x3cinput type\x3d"hidden" name\x3d"quantity" value\x3d\''+quantity+"' /\x3e"}else prodSelectParam='\x3cinput type\x3d"hidden" name\x3d"skuParam" value\x3d"" /\x3e\x3cinput type\x3d"hidden" name\x3d"selectParam" value\x3d"" /\x3e';var prodArray=basket.prodIdArray;if(prodArray.length==0){$("#prodInquireBasket ul").append("\x3cli prodId\x3d"+prodId+'\x3e\x3ca class\x3d"basket-list-img" href\x3d"javaScript:;" title\x3d""\x3e\x3cimg src\x3d"'+
prodPhotoUrl+'" height\x3d"45"\x3e\x3c/a\x3e\x3ca href\x3d"javaScript:;" title\x3d"" class\x3d"basket-list-name"\x3e'+prodName+"\x3c/a\x3e"+prodSelectParam+quantityStr+'\x3ca href\x3d"javaScript:;" class\x3d"basket-list-delate"\x3e'+phoenixSite.message(phoenixSite.lanEdition,"phoenix_common_delete")+"\x3c/a\x3e\x3c/li\x3e");var selectInquireCount=$("#selectInquireCount").html();$("#selectInquireCount").html(parseInt(selectInquireCount)+1);$("#shoppingIconNum").html(parseInt(selectInquireCount)+1);
$("#shoppingIconNum").removeClass("shoppingIconNum").addClass("shoppingIconNum");$(".shoppingBasketIcon").show();$("#prodInquireBasket").show();prodArray.push({"prodId":prodId,"prodPhotoUrl":prodPhotoUrl,"skuParam":skuParamStr,"selectParam":selectParamStr,"prodName":prodName,"quantity":quantity})}else{var isSimilar=false;prodArray.forEach(function(n){var item=n;var itemJson=item;if(itemJson.prodId==prodId)if(selectParamStr==itemJson.selectParam&&skuParamStr==itemJson.skuParam){isSimilar=true;return}});
if(!isSimilar){$("#prodInquireBasket ul").append("\x3cli prodId\x3d"+prodId+'\x3e\x3ca href\x3d"javaScript:;" title\x3d""\x3e\x3cimg src\x3d"'+prodPhotoUrl+'" height\x3d"45"\x3e\x3c/a\x3e\x3ca href\x3d"javaScript:;" title\x3d"" class\x3d"basket-list-name"\x3e'+prodName+"\x3c/a\x3e"+prodSelectParam+quantityStr+'\x3ca href\x3d"javaScript:;" class\x3d"basket-list-delate"\x3e'+phoenixSite.message(phoenixSite.lanEdition,"phoenix_common_delete")+"\x3c/a\x3e\x3c/li\x3e");var selectInquireCount=$("#selectInquireCount").html();
$("#selectInquireCount").html(parseInt(selectInquireCount)+1);$("#shoppingIconNum").html(parseInt(selectInquireCount)+1);prodArray.push({"prodId":prodId,"prodPhotoUrl":prodPhotoUrl,"skuParam":skuParamStr,"selectParam":selectParamStr,"prodName":prodName,"quantity":quantity})}}localStorage.setItem("baksetProdArray",JSON.stringify(prodArray));basket.bindDeleteInquireProd()});basket.bindDeleteInquireProd();$(document).on("click",".basket-list-img,.basket-list-name",function(){var prodId=$(this).parent().attr("prodId");
var _prod_options={url:"/phoenix/admin/prod/getProdUrl",data:{"prodId":prodId},done:function(result){if("error"==result)return;var page=phoenixSite.page||(phoenixSite.page={});var reg=new RegExp("^/");if(page._menu_prefix!=undefined&&reg.test(result))result=page._menu_prefix+result;location.href=result}};phoenixSite.ajax(_prod_options)})},bindDeleteInquireProd:function(){$(".basket-list-delate").unbind("click").bind("click",function(){if(!!!localStorage)return;var prodId=$(this).parent().attr("prodId");
var selectParam=$(this).parent().find("input[name\x3dselectParam]").val()||"";var selectSku=$(this).parent().find("input[name\x3dskuParam]").val()||"";$(this).parent().remove();prodIdArray=prodIdArray.filter(function(item){var itemJson=item;if(itemJson.prodId!=prodId)return true;else{if((itemJson.selectParam||"")==selectParam&&(itemJson.skuParam||"")==selectSku)return false;return true}});if(prodIdArray.length==0){$("#prodInquireBasket").slideUp();$(".shoppingBasketIcon").removeClass("on");$("#shoppingIconNum").html("");
$("#shoppingIconNum").removeClass("shoppingIconNum");$(".shoppingBasketIcon").hide();localStorage.setItem("baksetProdArray","")}else localStorage.setItem("baksetProdArray",JSON.stringify(prodIdArray));$("#selectInquireCount").html(prodIdArray.length);$("#shoppingIconNum").html(prodIdArray.length);if(!prodIdArray.length)$("#shoppingIconNum").html("");phoenixSite.basket.prodIdArray=prodIdArray});$(".inquire-basket-listwrap .basket-title .remove-basket-data").unbind("click").bind("click",function(){if(!!!localStorage)return;
$(".basket-lists li").each(function(){$(this).find(".basket-list-delate").trigger("click")});$("#selectInquireCount").text("0");$("#shoppingIconNum").html("");$("#shoppingIconNum span").removeClass("shoppingIconNum");localStorage.setItem("baksetProdArray","");$("#prodInquireBasket").slideUp();$(".shoppingBasketIcon").removeClass("on")})},submitInquireBasket:function(){var arrayInquire=new Array;$("#prodInquireBasket li").each(function(i,n){var selectParam=$("input[name\x3dselectParam]",this).val();
var skuParam=$("input[name\x3dskuParam]",this).val();var quantity=$("input[name\x3dquantity]",this).val();if(!quantity)quantity="";var inquireParam={};if(!!skuParam)inquireParam={"prodId":$(n).attr("prodId"),"skuParam":skuParam,"quantity":quantity};else inquireParam={"prodId":$(n).attr("prodId"),"selectParam":selectParam,"quantity":quantity};arrayInquire.push(inquireParam)});$("#basketForm input[name\x3dinquireParams]").val($.toJSON(arrayInquire))}})})(window,typeof jQuery==="undefined"?undefined:
jQuery);